SET NAMES utf8mb4;

-- CREATE AND USE DATABASE --
CREATE DATABASE IF NOT EXISTS openfoodfacts;
USE openfoodfacts;

-- CHECK AND AND REMOVE IF TABLES EXIST --
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS favorites;


-- CREATE CATEGORIES TABLES --
CREATE TABLE categories (
  	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  	Name VARCHAR(300) NOT NULL,
  	URL TEXT,
  	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


-- CREATE PRODUCTS TABLE --
CREATE TABLE products (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(300) NULL,
 	Brand VARCHAR(80) NULL,
 	Nutriscore CHAR(1) NULL,
 	URL TEXT,
 	Category_id SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;


-- CREATE FAVORITES TABLE --
CREATE TABLE favorites (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	product_id SMALLINT NOT NULL,
	Add_date DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
