SET NAMES utf8;

-- CREATE AND USE DATABASE --
CREATE DATABASE IF NOT EXISTS openfoodfact;
USE openfoodfact;

-- CHECK AND AND REMOVE IF TABLES EXIST --
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS favorites;


-- CREATE CATEGORIES TABLES --
CREATE TABLE categories (
  	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  	Name VARCHAR(70) NOT NULL,
  	URL VARCHAR(100) NOT NULL,
  	NB_Products MEDIUMINT UNSIGNED NOT NULL,
  	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- CREATE PRODUCTS TABLE --
CREATE TABLE products (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	Name VARCHAR(70) NOT NULL,
 	Designation TEXT,
 	Brand VARCHAR(80) NULL,
 	Nutriscore CHAR(1) NOT NULL,
 	Categorie_id SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- CREATE FAVORITES TABLE --
CREATE TABLE favorites (
	ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	product_id SMALLINT NOT NULL,
	Add_date DATETIME NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
